### ISSUE TITLE
Garland awards should sort players scores numerically, not alphabetically 

### ISSUE THREAD

**Issue by Dajakk** [tadeaustria/EverdellScore#19]
When player 1 has 11 cards of given type, and player 2 has 3 cards of the same type, then garland awards should award player 1 with 6 points and player 2 with 3 points, not the other way around.
Right now 11 and 3 are compared as strings, not as numbers, making "3" > "11"

**Comment by tadeaustria** [comment]
Thanks, for noticing. I think it is not that severe to create a new version for that, but will merge it then.
