### ISSUE TITLE
[Bug] [Newleaf] [Baker] Leftover resources missing

### ISSUE THREAD

**Issue by Dajakk** [tadeaustria/EverdellScore#33]
Replication scenario:
- Enable newleaf, no other expansions
- Add Baker to the town
- Leftover resources should be shown, but they are not present, Baker always gives +0 points

Since more and more cards require leftover resources, maybe it's time to enable it always? This would also possibly be less confusing for newer players/user as to when those sliders are shown

![image](https://github.com/tadeaustria/EverdellScore/assets/471436/946a0d37-a870-40b0-98a5-fe7a70222f7f)

![image](https://github.com/tadeaustria/EverdellScore/assets/471436/d822eb99-dda8-47e0-8a27-7aa670b6ec6d)

Also... when you disable sliders by removing the cards that enabled them, Baker still shows bonus points :D
![image](https://github.com/tadeaustria/EverdellScore/assets/471436/59d3d8a3-6ce6-42e4-a9f7-833932cab304)

**Comment by tadeaustria** [comment]
Yes, the bug is simply about the visibility. The idea was, to only show them, when they are really required, so save the user some time, he does not input something that does not have any influence.

But yes, the easiest way would be to show them always.
