### ISSUE TITLE
[Bug] [Pearlbrook] [Messenger] Occupied space

### ISSUE THREAD

**Issue by Dajakk** [tadeaustria/EverdellScore#34]
According to the Everdell Archive (and Pearlbrook manual), Messanger should share a space with a Construction if possible, but right now she always occupies a space.

![image](https://github.com/tadeaustria/EverdellScore/assets/471436/4d445206-91ea-4354-9cab-c481c322c540)

![image](https://github.com/tadeaustria/EverdellScore/assets/471436/6c6e390d-641d-42f6-bc93-7d332beabfa9)

It's almost certain the seconds case will ever occur, but the first one will -  most of the time (that is, occupancy should be either dynamic, or at least always 0)

**Comment by tadeaustria** [comment]
Very interesting. This fact is completely missing in the my German version of the rules. 
I would simply let him have 0 space. It would require to have 0 constructions in the end, he would end up with a separate space. Quite impossible, right?

**Comment by Dajakk** [comment]
> Quite impossible, right?

That would an achievement to get for sure! I bet there are people, who would try that :D

**Comment by Dajakk** [comment]
> Very interesting. This fact is completely missing in the my German version of the rules.

I've noticed German translation seems to be.... far from perfect 😱 
I'm trying to always reference both English and Polish manuals and Archives when checking this stuff

**Comment by tadeaustria** [comment]
I seems they just dropped it.
But besides that, I did not find many errors though...
Other fun fact: in Farshore, they even changed a card kind from Building to Critter.

**Comment by Dajakk** [comment]
> Other fun fact: in Farshore, they even changed a card kind from Building to Critter.

What card are you talking about? In Everdell Messenger is a critter too
