### ISSUE TITLE
Hopewatch Gate has wrong score

### ISSUE THREAD

**Issue by sterlingewright** [tadeaustria/EverdellScore#8]
This is a great app and helped speed up scoring.  One thing I noticed for Pearlbrook, the wonder Hopwatch Gate showed that it is worth 20 points in the app. It is only worth 10.

**Comment by tadeaustria** [comment]
Thank you for your positive feedback. I am glad this helps.
Thank you also for noticing this bug. I will soon release an update with also some bugfixes for spirecrest.
